apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: dummy action
inputs:
  string-val:  # id of input
    description: 'sample string'
    required: false


runs:
     using: composite
  steps:
    - id: invoke-action
      name: invoke-action
      uses: docker://golang:1.20.3-alpine3.17 
      shell: sh
      run: |
        echo "env ${{inputs.string-val}}"
        

