apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: dummy action
inputs:
  string-val:  # id of input
    description: 'sample string'
    required: false


runs:
  using: composite
  steps:
    - id: invoke-action
      name: invoke-action
      uses: docker://golang:1.20.3-alpine3.17 
      shell: sh
      run: |
        echo "before masking" 
        echo "${{inputs.string-val}}" 
        echo "after masking" 
        echo -n "${{inputs.string-val}}" | cloudbees mask
        echo -n "${{inputs.string-val}}"
        

    - id: invoke-action-1
      name: invoke-action
      uses: docker://golang:1.20.3-alpine3.17 
      shell: sh
      run: |
        echo "Exiting due to error: <your message here>" >&2
        exit 1
